DEBUG:signac.common.config:Reading config file '/home/jacobbieri/projects/persistence-length/signac.rc'.
DEBUG:signac.contrib.project:The project's schema version 1 is supported.
Using environment configuration: Fry
DEBUG:flow.project:Entering buffered mode.
DEBUG:flow.project:Exiting buffered mode.
INFO:flow.project:Executing 1 operation(s) (Pass #01)...
INFO:flow.project:Execute operation 'test-sim1(b5eebd26cfeaccbea1517d55ab567820)'...
DEBUG:flow.project:Forking to execute operation 'test-sim1(b5eebd26cfeaccbea1517d55ab567820)' with cmd 'python -u /home/jacobbieri/projects/persistence-length/project.py exec test-sim1 b5eebd26cfeaccbea1517d55ab567820'.
DEBUG:signac.common.config:Reading config file '/home/jacobbieri/projects/persistence-length/signac.rc'.
DEBUG:signac.contrib.project:The project's schema version 1 is supported.
Using environment configuration: Fry
Traceback (most recent call last):
  File "/home/jacobbieri/projects/persistence-length/project.py", line 249, in <module>
    MyProject(environment=Fry).main()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 5134, in main
    args.func(args)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 4878, in _main_exec
    operation_function(*aggregate)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 625, in __call__
    return self._op_func(*jobs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jacobbieri/projects/persistence-length/project.py", line 80, in sample
    import hoomd_polymers
ModuleNotFoundError: No module named 'hoomd_polymers'
Traceback (most recent call last):
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3461, in _execute_operation
    subprocess.run(
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python -u /home/jacobbieri/projects/persistence-length/project.py exec test-sim1 b5eebd26cfeaccbea1517d55ab567820' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacobbieri/projects/persistence-length/project.py", line 249, in <module>
    MyProject(environment=Fry).main()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 5134, in main
    args.func(args)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 4846, in _main_run
    run()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3720, in run
    self._run_operations(
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3305, in _run_operations
    self._execute_operation(operation, timeout, pretend)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3465, in _execute_operation
    raise UserOperationError(execution_error_message) from error
flow.errors.UserOperationError: An exception was raised during operation test-sim1 for job or aggregate with id b5eebd26cfeaccbea1517d55ab567820.
